Task Completed
RohanSingh-inno/Custom-Module pull request #1
Opened 2023-06-26 14:01 UTC by RohanSingh-inno

2023-07-08 18:32 UTC, vivekpan27 commented
Please first check if files which have been pushed are correct or not.
I can see some files which are not supposed to be pushed.

2023-07-10 08:10 UTC, vivekpan27 commented
@RohanSingh-inno Please resolve the comment ASAP.

2023-07-10 10:09 UTC, RohanSingh-inno commented
ok sir

2023-07-10 12:11 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.info.yml
> +name: first custom module
```
name: First custom module
```

2023-07-10 12:16 UTC, vivekpan27 requested changes

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.info.yml
> +core_version_requirement: ^9 || ^10
core_version_requirement: ^10

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.links.menu.yml
> +  route_name: first_custom_module.Page1
There are no quotes here in the RHS and in the next link you have added quotes.
Please try to follow a single approach.
Check in core files how it is done.

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.links.menu.yml
> +      target: '_blank'
This red circle indicates that the new line at end of file is missing.
Did you run the code through the plugin I mentioned in slack?

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.permissions.yml
> +  description: You can change the value of this
Same red circle here

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.routing.yml
> +    _controller: 'Drupal\first_custom_module\Controller\BasicPageController::Page1'
does class function name ever start with a capital letter?

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.routing.yml
> +first_custom_module.Page1:
```
first_custom_module.page1:
```

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.routing.yml
> +  path: '/Page1'
Does path ever start with a capital letter?

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/src/Controller/BasicPageController.php
> +{
The curly braces should start in the prevous line or this line?

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/src/Controller/BasicPageController.php
> +        $user = \Drupal::currentUser()->getAccountName();
This kind of service calling is not acceptable in classes.
Please use dependency injection here.

2023-07-10 12:16 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/src/Controller/BasicPageController.php
> +    }
Indentation is all wrong.

2023-07-11 03:40 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/first_custom_module.permissions.yml
> +  description: You can change the value of this
not fixed still

2023-07-11 03:42 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/src/Controller/BasicPageController.php
> +    protected $account;
Function docblock missing.

2023-07-11 03:42 UTC, vivekpan27 commented on web/modules/custom/first_custom_module/src/Controller/BasicPageController.php
> +    }
It's still wrong.

2023-07-11 03:43 UTC, vivekpan27 requested changes
Did you run the code through Drupal code sniffer as mentioned yesterday?
I don't think so.
Run it on your custom module folder, make fixes, then assign the PR back for review.

2023-07-11 11:30 UTC, merged